language: php

php:
    - 7.3
    - 7.4
    - 8.0

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist -vvv

script:
    - php vendor/bin/phpunit

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover log/coverage.xml
    - wget https://tomzx.github.io/php-semver-checker-git/php-semver-checker-git.phar
    - php php-semver-checker-git.phar suggest --allow-detached -vvv --details --include-before=src --include-after=src
